source("read_data.R")
data <- read_data()

png("data/plot3.png", width=480, height=480)
plot(data$datetime, data$Sub_metering_1, type="n", xlab="", ylab="Energy submetering")
lines(data$datetime, data$Sub_metering_1, col="black")
lines(data$datetime, data$Sub_metering_2, col="red")
lines(data$datetime, data$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1)
dev.off()
